/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package conta_cliente;

/**
 *
 * @author EDGARD
 */
public class jfAgiotex extends javax.swing.JFrame {

    /**
     * Creates new form jfAgiotex
     */
    public jfAgiotex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfPrimeiroNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfSegundoNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNroConta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfSaldo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbOK = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbGravar = new javax.swing.JButton();
        jbAbrir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agiotex");

        jLabel1.setText("CPF:");

        jLabel2.setText("Primeiro Nome:");

        jLabel3.setText("Segundo Nome:");

        jLabel4.setText("Número da Conta:");

        jLabel5.setText("Saldo:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jbOK.setText("OK");
        jbOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbOKMouseClicked(evt);
            }
        });

        jbLimpar.setText("LIMPAR");
        jbLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbLimparMouseClicked(evt);
            }
        });

        jbGravar.setText("GRAVAR");
        jbGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbGravarMouseClicked(evt);
            }
        });

        jbAbrir.setText("ABRIR");
        jbAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAbrirMouseClicked(evt);
            }
        });

        jbFechar.setText("FECHAR ARQUIVO");
        jbFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfSegundoNome))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfNroConta))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAbrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFechar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfNroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfSegundoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGravar)
                    .addComponent(jbAbrir)
                    .addComponent(jbFechar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbOKMouseClicked
        // TODO add your handling code here:
        String  tempCPF;
        int     tempNroConta;
        String  tempPrimeiroNome;
        String  tempSegundoNome;
        double  tempSaldo;
        
        tempCPF = jtfCPF.getText(); 
        tempNroConta = Integer.parseInt(jtfNroConta.getText()); 
        tempPrimeiroNome = jtfPrimeiroNome.getText();
        tempSegundoNome = jtfSegundoNome.getText();
        tempSaldo = Double.parseDouble(jtfSaldo.getText());
        
        ContaCliente  c = new ContaCliente();
        
        ContaCliente c3 = new ContaCliente(jtfCPF.getText(),
                Integer.parseInt(jtfNroConta.getText()), 
                jtfPrimeiroNome.getText(),
                jtfSegundoNome.getText(), 
                Double.parseDouble(jtfSaldo.getText()));
        
        c.setCPF(tempCPF);
        c.setNumero_conta(tempNroConta);
        c.setPrimeiro_nome(tempPrimeiroNome);
        c.setSegundo_nome(tempSegundoNome);
        c.setSaldo(tempSaldo);
        
        c.imprime();
        
    }//GEN-LAST:event_jbOKMouseClicked

    private void jbLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLimparMouseClicked
        // TODO add your handling code here:
        jtfCPF.setText(null);
        jtfNroConta.setText(null);
        jtfPrimeiroNome.setText(null);
        jtfSegundoNome.setText(null);
        jtfSaldo.setText(null);
    }//GEN-LAST:event_jbLimparMouseClicked

    private void jbAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAbrirMouseClicked
        arquivoConta.abreArquivoGrava();
    }//GEN-LAST:event_jbAbrirMouseClicked

    private void jbGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGravarMouseClicked
        ContaCliente conta = new ContaCliente(jtfCPF.getText(),
                Integer.parseInt(jtfNroConta.getText()), 
                jtfPrimeiroNome.getText(),
                jtfSegundoNome.getText(), 
                Double.parseDouble(jtfSaldo.getText()));
        
        arquivoConta.adicionaRegistro(conta.getCPF(), conta.getNumero_conta(),
                conta.getPrimeiro_nome(), conta.getSegundo_nome(),
                conta.getSaldo());
    }//GEN-LAST:event_jbGravarMouseClicked

    private void jbFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFecharMouseClicked
        arquivoConta.fechaArquivoGrava();
    }//GEN-LAST:event_jbFecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfAgiotex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfAgiotex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfAgiotex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfAgiotex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfAgiotex().setVisible(true);
            }
        });
        
        ContaCliente  c1 = new ContaCliente("481.818.036-04",
                55, "Edgard", "Lamounier", 23.18);
        
        ContaCliente  c2 = new ContaCliente("784.658.852-22",
                66, "Mauro", "França", 673.18);
        
        c1.imprime();
        c2.imprime();   
        
//        ArquivoTexto  arquivoConta = new ArquivoTexto();
//        
//        arquivoConta.abreArquivoGrava();
//        
//        arquivoConta.adicionaRegistro(c1.getCPF(), 
//                c1.getNumero_conta(), c1.getPrimeiro_nome(), 
//                c1.getSegundo_nome(), c1.getSaldo());
//        
//        arquivoConta.adicionaRegistro(c2.getCPF(), 
//                c2.getNumero_conta(), c2.getPrimeiro_nome(), 
//                c2.getSegundo_nome(), c2.getSaldo());
//        
//        arquivoConta.fechaArquivoGrava();
    } // fim do metodo main
    
    private ArquivoTexto  arquivoConta = new ArquivoTexto();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbAbrir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbOK;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfNroConta;
    private javax.swing.JTextField jtfPrimeiroNome;
    private javax.swing.JTextField jtfSaldo;
    private javax.swing.JTextField jtfSegundoNome;
    // End of variables declaration//GEN-END:variables
}
